### ISSUE TITLE
评论功能用不了

### ISSUE THREAD

**Issue by chen-assert** [amaothree/amaothree.github.io#1]
点击从github登陆后直接跳转回了主界面
链接显示为:
https://suiyuehao.xyz/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch
环境:chrome 71.0.3578.98 Win10x64

**Comment by amaothree** [comment]
现在已经修正，请登录github账号重试。
